version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: warehouse-backend-prod
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.production
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - warehouse-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: warehouse-frontend-prod
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - warehouse-network

  nginx:
    image: nginx:alpine
    container_name: warehouse-nginx-prod
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - warehouse-network

networks:
  warehouse-network:
    driver: bridge

volumes:
  uploads:
